services:
    onesky.adapter:
        class:        Evozon\TranslatrBundle\Clients\OneSkyAdapter
        arguments:
            - '@event_dispatcher'

    null.adapter:
        class:        Evozon\TranslatrBundle\Clients\NullAdapter

    client:
        class:        Evozon\TranslatrBundle\Clients\NullAdapter

    uploader:
        class:        Evozon\TranslatrBundle\OneSky\Uploader
        arguments:
            - '@client'
            - '%evozon_translatr.project%'
            - '%evozon_translatr.locale_format%'