services:
    uploader:
        class:        Evozon\TranslatrBundle\OneSky\Uploader
        arguments:
            - '@client'
            - '%kernel.root_dir%'

    downloader:
        class:        Evozon\TranslatrBundle\OneSky\Downloader
        arguments:
            - '@client'
            - '%kernel.root_dir%'