services:
    uploader:
        class:        Evozon\TranslatrBundle\Service\Uploader
        arguments:
            - '@client'
            - '%kernel.root_dir%'

    downloader:
        class:        Evozon\TranslatrBundle\Service\Downloader
        arguments:
            - '@client'
            - '%kernel.root_dir%'