services:
    onesky.adapter:
        class:        Evozon\TranslatrBundle\Clients\OneSkyAdapter
        arguments:
            - "@event_dispatcher"

    uploader:
        class:        Evozon\TranslatrBundle\OneSky\Uploader