services:
    uploader:
        class:        Evozon\TranslatrBundle\OneSky\Uploader
        arguments:
            - '@client'

    downloader:
        class:        Evozon\TranslatrBundle\OneSky\Downloader
        arguments:
            - '@client'